// Generated by scripts/vendor.mjs when switching to locally hosted dependencies.
// Exact versions: never use a floating "latest" URL in a release.
export const RUNTIME_URLS = Object.freeze({
  marked: 'https://cdn.jsdelivr.net/npm/marked@18.0.11/lib/marked.umd.js',
  purify: 'https://cdnjs.cloudflare.com/ajax/libs/dompurify/3.4.14/purify.min.js',
  highlight: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.12.0/highlight.min.js',
});
export const RUNTIME_MODE = 'cdn';
