/** Explicit, opt-in vendoring. Never silently substitute another library version. */
import { mkdir, readFile, writeFile, rename } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const root = new URL('../', import.meta.url);
const specs = [
  { key:'marked', file:'marked.umd.js', url:'https://cdn.jsdelivr.net/npm/marked@18.0.11/lib/marked.umd.js', version:'18.0.11', license:'https://cdn.jsdelivr.net/npm/marked@18.0.11/LICENSE', licenseFile:'LICENSE-marked.txt' },
  { key:'purify', file:'purify.min.js', url:'https://cdnjs.cloudflare.com/ajax/libs/dompurify/3.4.14/purify.min.js', version:'3.4.14', license:'https://cdn.jsdelivr.net/npm/dompurify@3.4.14/LICENSE', licenseFile:'LICENSE-DOMPurify.txt' },
  { key:'highlight', file:'highlight.min.js', url:'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.12.0/highlight.min.js', version:'11.12.0', license:'https://cdn.jsdelivr.net/npm/highlight.js@11.12.0/LICENSE', licenseFile:'LICENSE-highlight.txt' },
];
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
if (process.argv.includes('--check')) {
  const manifest = JSON.parse(await readFile(new URL('vendor/manifest.json', root), 'utf8'));
  for (const item of manifest.files) {
    if (hash(await readFile(new URL(`vendor/${item.file}`, root))) !== item.sha256) throw new Error(`Integrity mismatch: ${item.file}`);
  }
  console.log(`Verified ${manifest.files.length} vendored file hashes.`);
} else {
  await mkdir(new URL('vendor/', root), { recursive: true });
  const files = [];
  for (const spec of specs) {
    for (const [url, file, isCode] of [[spec.url, spec.file, true], [spec.license, spec.licenseFile, false]]) {
      const response = await fetch(url, { signal: AbortSignal.timeout(30000), redirect: 'error' });
      if (!response.ok) throw new Error(`Download failed: ${url} (${response.status})`);
      const bytes = Buffer.from(await response.arrayBuffer());
      const text = bytes.toString('utf8');
      if (isCode && (text.length < 1000 || !text.includes(spec.version) || /^\s*<!doctype/i.test(text))) throw new Error(`Unexpected library content: ${file}`);
      await writeFile(new URL(`vendor/${file}.tmp`, root), bytes);
      await rename(new URL(`vendor/${file}.tmp`, root), new URL(`vendor/${file}`, root));
      files.push({ file, url, version: spec.version, sha256: hash(bytes) });
    }
  }
  // Switch the runtime ONLY after every dependency and license has been downloaded.
  await writeFile(new URL('vendor/manifest.json', root), JSON.stringify({ generatedAt: new Date().toISOString(), files }, null, 2) + '\n');
  const urls = Object.fromEntries(specs.map(spec => [spec.key, `../vendor/${spec.file}`]));
  await writeFile(new URL('js/runtime-urls.js', root), `// Generated by npm run vendor. Review vendor/manifest.json before committing.\nexport const RUNTIME_URLS = Object.freeze(${JSON.stringify(urls, null, 2)});\nexport const RUNTIME_MODE = 'local';\n`);
  await import('./stamp-release.mjs');
  console.log('Vendored exact dependency versions and licenses. Commit vendor/ and js/runtime-urls.js together.');
}
